cache:
  paths:
    - .m2/

stages:
 - build
 - test
 - deploy
 - deliver

compile:
 stage: build
 script: "mvn compile -U -B"
 artifacts:
  expire_in: 15 minutes
  paths:
  - "*/target/*"
 tags:
 - mvn
 - jdk8

test-compile:
 stage: build
 script: "mvn test-compile -U -B"
 artifacts:
  expire_in: 15 minutes
  paths:
  - "*/target/*"
 tags:
 - mvn
 - jdk8

unit-tests:
 stage: test
 script: "mvn compile -Dcheckstyle.skip=true jacoco:prepare-agent surefire:test -B"
 artifacts:
   expire_in: 15 minutes
   paths:
   - "*/target/*.exec"
 tags:
 - mvn
 - jdk8
